# Generated by Django 5.0.4 on 2024-11-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="created",
            new_name="created_at",
        ),
    ]
